### ISSUE TITLE
SMOKE python部署问题（trt加速推理）

### ISSUE THREAD

**Issue by finsary** [PaddlePaddle/Paddle3D#149]
os：ubuntu 18.04
paddle: 2.4.0
python 3.6
cuda 10.2
cudnn 7.6.5
tensorrt 7.0.0.11在python部署的执行TRT部署的步骤中，加载--dynamic_shape_file指定的模型动态shape信息，使用FP32精度进行预测，加上关键字--use_gpu  --use_trt后，报错(部分）： 
I1212 15:26:12.890170 18103 tensorrt_subgraph_pass.cc:244] ---  detect a sub-graph with 4 nodes
I1212 15:26:12.895742 18103 tensorrt_subgraph_pass.cc:560] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1212 15:26:12.901537 18103 engine.cc:199] Run Paddle-TRT Dynamic Shape mode.
**E1212 15:26:12.901681 18103 helper.h:114] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })**

其中加粗部分错误重复上百行，模型下载的readme中的预训练model，
下列为最后几行的错误：
I1212 15:26:24.284873 18103 engine.cc:684] Inspector needs TensorRT version 8.2 and after.
I1212 15:26:24.286538 18103 tensorrt_subgraph_pass.cc:244] ---  detect a sub-graph with 64 nodes
I1212 15:26:24.306820 18103 tensorrt_subgraph_pass.cc:560] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1212 15:26:24.312911 18103 op_converter.h:160] There is no OpConverter for type gather_nd, now use generic_plugin_creater!
W1212 15:26:24.313999 18103 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 10.2
W1212 15:26:24.358321 18103 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
I1212 15:26:24.358857 18103 op_converter.h:160] There is no OpConverter for type gather_nd, now use generic_plugin_creater!
I1212 15:26:24.359781 18103 op_converter.h:160] There is no OpConverter for type gather_nd, now use generic_plugin_creater!
I1212 15:26:24.361145 18103 op_converter.h:160] There is no OpConverter for type gather_nd, now use generic_plugin_creater!
E1212 15:26:24.362473 18103 helper.h:114] (Unnamed Layer* 114) [Shuffle]: input and output volume mismatch. input volume is 50 and output volume is 500

**未改动源代码**，同时readme中所有的trt部署指令都未加--use_gpu, 实测是必须加上的（不然显存不变，为cpu运行），同时smoke中的python trt部署中--collect_shape_info关键字应为--collect_dynamic_shape_info,期待修改

**Comment by finsary** [comment]
前面的步骤都是正常运行的，只使用--use_gpu时同样正常运行

**Comment by finsary** [comment]
gcc -v 7.5.0

**Comment by finsary** [comment]
将gcc版本升级为8.4，依旧报上百行如下错误：
E1212 15:26:12.901681 18103 helper.h:114] Parameter check failed at: optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int x) { return x > 0; })

**Comment by finsary** [comment]
今天测试发现smoke_dla与smoke_hrnet都存在这样的问题，同样会有上百行的重复报错，smoke_hrnet的Traceback如下：
Traceback (most recent call last):
  File "infer.py", line 134, in <module>
    pred = init_predictor(args)
  File "infer.py", line 106, in init_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Errors occures in Paddle-TRT reshape2 op, try to use C++ Api config.Exp_DisableTensorRtOPs({"reshape2"})
; or Python Api config.exp_disable_tensorrt_ops(["reshape2"]) to forbid reshape2 op into Paddle-TRT.
  [Hint: Expected layer->getOutput(0)->getDimensions().nbDims >= 0, but received layer->getOutput(0)->getDimensions().nbDims:-1 < 0:0.] (at /paddle/paddle/fluid/inference/tensorrt/convert/reshape_op.cc:82)

**Comment by nepeplwu** [comment]
@finsary 感谢反馈，我们用其他的环境目前复现了类似的问题，正在跟进中，有进展会在这里同步，可以先不开启trt进行验证

**Comment by Lyric0620** [comment]
请问这个问题解决了吗

**Comment by nepeplwu** [comment]
@Yutong-gannis 可以试试在config里面加上`config.exp_disable_tensorrt_ops(["reshape2"])`看看
