### ISSUE TITLE
训练pointpillars算法时报错

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#222]
1、按照[readme](https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/pointpillars)训练；

    python -m paddle.distributed.launch --gpus 0 \
        tools/train.py \
        --config configs/pointpillars/pointpillars_xyres16_kitti_car.yml \
        --save_interval 1856 \
        --keep_checkpoint_max 100 \
        --save_dir outputs/pointpillars \
        --do_eval \
        --num_workers 8

在1856step跑完eval后会报错如下，不加--do_eval可以正常训练，请问要怎么处理呢？

2023-01-18 12:34:44,859 -     INFO - iou3d_nms_cuda builded success!
2023-01-18 12:38:55,261 -     INFO - [##################################################] 100.00%
2023-01-18 12:38:55,262 -     INFO - 
2023-01-18 12:40:12,682 -     INFO - Car:
2023-01-18 12:40:12,682 -     INFO - BBOX AP_R40@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - BEV  AP_R40@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - 3D   AP_R40@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - BBOX AP_R40@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - BEV  AP_R40@50%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - 3D   AP_R40@50%: 0.00 0.00 0.00
2023-01-18 12:40:12,682 -     INFO - Car:
2023-01-18 12:40:12,683 -     INFO - BBOX AP_R11@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,683 -     INFO - BEV  AP_R11@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,683 -     INFO - 3D   AP_R11@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,683 -     INFO - BBOX AP_R11@70%: 0.00 0.00 0.00
2023-01-18 12:40:12,683 -     INFO - BEV  AP_R11@50%: 0.00 0.00 0.00
2023-01-18 12:40:12,683 -     INFO - 3D   AP_R11@50%: 0.00 0.00 0.00
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(args)
  File "tools/train.py", line 197, in main
    trainer.train()
  File "/mnt/docker_share/Project/Paddle3D/paddle3d/apis/trainer.py", line 328, in train
    for k, v in metrics.items():
AttributeError: 'tuple' object has no attribute 'items'
LAUNCH INFO 2023-01-18 12:40:15,584 Exit code 1

2、PS：请问pointpillars、centerpoint等推理代码等需要贡献可视化代码吗？

**Comment by FlyingQianMM** [comment]
这是因为模型稍微收敛，此时做验证的话精度返回为空导致错误发生。可以把--do_eval去掉，不要边训边验证。模型训练完之后再评估精度。

如果您已经开发可视化代码，非常欢迎您提pr。

**Comment by Kerry678231** [comment]
好的，谢谢，我最近整理一下代码发出；
ps:有个不情之请想问下，你们组还有人员需求吗？我前段时间把按照paddle的smoke用torch复写了一下，还是对这种框架的开发很有兴趣的，而且对百度的开源精神，很敬佩。。
