### ISSUE TITLE
训练centerpoint时报错:ERROR - voxelize builded fail!ERROR - voxelize builded fail!

### ISSUE THREAD

**Issue by rainaider** [PaddlePaddle/Paddle3D#244]
conda 环境 python3.8 gcc-8.2 ubuntu18.04 cudnn 7.6.5
分析是cc 没有找到编译器  我是从gcc-7.5升级到8.2的，如何配置cc

以下是信息：
  - dim: 4
    type: LoadPointCloud
    use_dim: 4
  - type: RemoveCameraInvisiblePointsKITTI
  type: KittiPCDataset
------------------------------------------------
2023-02-09 21:05:11,719 -     INFO - Finish CenterHead Initialization
2023-02-09 21:05:26,291 -  WARNING - No custom op voxelize found, try JIT build
Compiling user custom op, it will cost a few seconds.....
cc: No such file or directory
error: command '/usr/local/cuda-10.2/bin/nvcc' failed with exit code 1
2023-02-09 21:05:30,158 -    ERROR - voxelize builded fail!
Traceback (most recent call last):
  File "/export/jd_arch/Paddle3D/paddle3d/ops/__init__.py", line 164, in _load_module
    self.module = importlib.import_module(self.modulename)
  File "/root/miniconda3/envs/paddle3d/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'voxelize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle3d/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1152, in run_cmd
    return subprocess.check_call(command, shell=True, stdout=DEVNULL)
  File "/root/miniconda3/envs/paddle3d/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /root/.cache/paddle_extensions && /root/miniconda3/envs/paddle3d/bin/python voxelize_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(args)

**Comment by FlyingQianMM** [comment]
看你这个报错，是nvcc有问题，导致自定义算子编译失败：
```
Compiling user custom op, it will cost a few seconds.....
cc: No such file or directory
error: command '/usr/local/cuda-10.2/bin/nvcc' failed with exit code 1
2023-02-09 21:05:30,158 - ERROR - voxelize builded fail!
```
检查下nvcc安装和环境变量设置是否有问题

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
