### ISSUE TITLE
当我尝试用KITTI数据集训练pointpilliars模型，在模型验证时报了：paddle3d-1.0.0-py3.7.egg/paddle3d/apis/trainer.py", line 328, in train，    for k, v in metrics.items(): AttributeError: 'tuple' object has no attribute 'items'的问题。

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#258]
相关报错如下:
........................
2023-03-07 19:38:11,758 -     INFO - [TRAIN] epoch=2/326, iter=950/296960 , total_loss=1.299116, lr=0.000200 | ETA 33:32:52
2023-03-07 19:38:15,929 -     INFO - [TRAIN] epoch=2/326, iter=960/296960 , total_loss=1.253693, lr=0.000200 | ETA 34:19:23
2023-03-07 19:38:20,140 -     INFO - [TRAIN] epoch=2/326, iter=970/296960 , total_loss=1.287663, lr=0.000200 | ETA 34:23:52
2023-03-07 19:38:24,328 -     INFO - [TRAIN] epoch=2/326, iter=980/296960 , total_loss=1.322549, lr=0.000200 | ETA 34:40:58
2023-03-07 19:38:28,475 -     INFO - [TRAIN] epoch=2/326, iter=990/296960 , total_loss=1.375352, lr=0.000200 | ETA 33:51:31
2023-03-07 19:38:32,611 -     INFO - [TRAIN] epoch=2/326, iter=1000/296960 , total_loss=1.336525, lr=0.000200 | ETA 33:42:13
2023-03-07 19:38:34,854 -     INFO - evaluate on validate dataset
2023-03-07 19:38:37,556 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build
Compiling user custom op, it will cost a few seconds.....
2023-03-07 19:38:39,739 -     INFO - iou3d_nms_cuda builded success!
2023-03-07 19:41:03,047 -     INFO - [##################################################] 100.00%
2023-03-07 19:41:03,047 -     INFO - 
2023-03-07 19:41:33,729 -     INFO - Car:
2023-03-07 19:41:33,730 -     INFO - BBOX AP_R40@70%: 16.62 16.65 14.06
2023-03-07 19:41:33,730 -     INFO - BEV  AP_R40@70%: 17.95 19.03 15.55
2023-03-07 19:41:33,730 -     INFO - 3D   AP_R40@70%: 4.64 4.62 3.68
2023-03-07 19:41:33,730 -     INFO - BBOX AP_R40@70%: 16.62 16.65 14.06
2023-03-07 19:41:33,730 -     INFO - BEV  AP_R40@50%: 34.20 37.64 32.79
2023-03-07 19:41:33,730 -     INFO - 3D   AP_R40@50%: 28.70 29.83 25.53
2023-03-07 19:41:33,730 -     INFO - Car:
2023-03-07 19:41:33,730 -     INFO - BBOX AP_R11@70%: 16.90 17.44 15.16
2023-03-07 19:41:33,730 -     INFO - BEV  AP_R11@70%: 18.12 19.73 16.67
2023-03-07 19:41:33,730 -     INFO - 3D   AP_R11@70%: 5.16 5.81 4.84
2023-03-07 19:41:33,730 -     INFO - BBOX AP_R11@70%: 16.90 17.44 15.16
2023-03-07 19:41:33,730 -     INFO - BEV  AP_R11@50%: 33.74 37.46 33.13
2023-03-07 19:41:33,730 -     INFO - 3D   AP_R11@50%: 28.37 30.10 26.15
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main(args)
  File "tools/train.py", line 197, in main
    trainer.train()
  File "/home/les/miniconda3/envs/paddle3d_py37_cu102/lib/python3.7/site-packages/paddle3d-1.0.0-py3.7.egg/paddle3d/apis/trainer.py", line 328, in train
    for k, v in metrics.items():
AttributeError: 'tuple' object has no attribute 'items'
LAUNCH INFO 2023-03-07 19:41:34,486 Pod failed
LAUNCH ERROR 2023-03-07 19:41:34,487 Container failed !!!

请问这个有遇到过吗，可以用什么方式解决呢？

**Comment by Birdylx** [comment]
@cxy86121 hi，看log你是边训练边评估，有尝试用提供的预训练模型直接评估吗？看样子是评估其它类别的时候出的错

**Comment by cxy86121** [comment]
> @cxy86121 hi，看log你是边训练边评估，有尝试用提供的预训练模型直接评估吗？看样子是评估其它类别的时候出的错

使用预训练的模型直接评估没有问题；其次在训练时屏蔽评估，当训练完成后再进行评估也是可以的~
