### ISSUE TITLE
Install Paddle3D ERROR (pip install -e .  # install in edit mode)

### ISSUE THREAD

**Issue by HezyC** [PaddlePaddle/Paddle3D#316]
Hi,

Under the GPU platform, follow the steps in https://github.com/PaddlePaddle/Paddle3D/blob/develop/docs/installation.md, installing Paddle3D will report the following error, can you take a look?

Python = 3.8
CUDA = 11.7

Error message:

(py38) C:\Users\C.Hezy\Paddle3D>pip install -e .
Obtaining file:///C:/Users/C.Hezy/Paddle3D
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      2023-04-18 21:17:26,506 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build
      Traceback (most recent call last):
        File "iou3d_nms_cuda_setup.py", line 9, in <module>
          CUDAExtension(
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\cpp_extension.py", line 334, in CUDAExtension
          kwargs = normalize_extension_kwargs(kwargs, use_cuda=True)
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 484, in normalize_extension_kwargs
          include_dirs.extend(find_paddle_includes(use_cuda))
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 701, in find_paddle_includes
          cuda_include_dir = find_cuda_includes()
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 667, in find_cuda_includes
          raise ValueError(
      ValueError: Not found CUDA runtime, please use `export CUDA_HOME=XXX` to specific it.
      2023-04-18 21:17:28,980 -    ERROR - iou3d_nms_cuda builded fail!
      Traceback (most recent call last):
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\ops\__init__.py", line 156, in _load_module
          self.module = importlib.import_module(self.modulename)
        File "D:\software\Anaconda\envs\py38\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'iou3d_nms_cuda'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1152, in run_cmd
          return subprocess.check_call(command, shell=True, stdout=DEVNULL)
        File "D:\software\Anaconda\envs\py38\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cd /d C:\Users\C.Hezy\.cache\paddle_extensions && D:\software\Anaconda\envs\py38\python.exe iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\C.Hezy\Paddle3D\setup.py", line 20, in <module>
          import paddle3d
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\__init__.py", line 28, in <module>
          from . import datasets, models, transforms
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\datasets\__init__.py", line 16, in <module>
          from .kitti import KittiDepthDataset, KittiMonoDataset, KittiPCDataset
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\datasets\kitti\__init__.py", line 15, in <module>
          from .kitti_depth_det import KittiDepthDataset
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\datasets\kitti\kitti_depth_det.py", line 26, in <module>
          import paddle3d.transforms as T
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\transforms\__init__.py", line 19, in <module>
          from paddle3d.transforms.reader import *
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\transforms\reader.py", line 30, in <module>
          from paddle3d.models.detection.bevfusion.utils import generate_guassian_depth_target, map_pointcloud_to_image
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\models\__init__.py", line 18, in <module>
          from .heads import *
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\models\heads\__init__.py", line 16, in <module>
          from .dense_heads import *
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\models\heads\dense_heads\__init__.py", line 15, in <module>
          from .anchor3d_head import *
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\models\heads\dense_heads\anchor3d_head.py", line 23, in <module>
          from paddle3d.models.detection.bevfusion.utils import box3d_multiclass_nms
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\models\detection\bevfusion\utils.py", line 23, in <module>
          from paddle3d.ops.iou3d_nms_cuda import nms_gpu
        File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\ops\__init__.py", line 174, in __getattr__
          module = self._load_module()
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\ops\__init__.py", line 160, in _load_module
          self.module = self.jit_build()
        File "C:\Users\C.Hezy\Paddle3D\paddle3d\ops\__init__.py", line 147, in jit_build
          return paddle_jit_load(
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\cpp_extension.py", line 944, in load
          _jit_compile(file_path, verbose)
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1113, in _jit_compile
          run_cmd(compile_cmd, verbose)
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1155, in run_cmd
          raise RuntimeError("Failed to run command: {}, errors: {}".format(
      RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /d C:\Users\C.Hezy\.cache\paddle_extensions && D:\software\Anaconda\envs\py38\python.exe iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.
      Compiling user custom op, it will cost a few seconds.....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cxy86121** [comment]
mybe cuda error:
1.first in Terminal：sudo ln -s /usr/local/cuda-xxx (your cuda version) /usr/local/cuda
2.then open bashrc file: vim ~/.bashrc
add: 
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH

press "Esc" keyboard and write   ":wq"   for   save and exit 

3.in Terminal do : (1)source ~/.bashrc      (2)ldconfig
then reboot your computer.

**Comment by HezyC** [comment]
**Thank you very much for your reply. 
I have modified the configuration of CUDA, and now there are no CUDA errors, but Paddle3D still cannot be installed. 
The problem is similar to before, with the following specific issues:**

(py38) D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D>pip install -e .
Obtaining file:///D:/software/Anaconda/envs/py38/Lib/site-packages/Paddle3D
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      2023-04-20 14:44:18,937 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build
      error: command 'E:\\vs\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      2023-04-20 14:44:23,892 -    ERROR - iou3d_nms_cuda builded fail!
      Traceback (most recent call last):
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\ops\__init__.py", line 156, in _load_module
          self.module = importlib.import_module(self.modulename)
        File "D:\software\Anaconda\envs\py38\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'iou3d_nms_cuda'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1152, in run_cmd
          return subprocess.check_call(command, shell=True, stdout=DEVNULL)
        File "D:\software\Anaconda\envs\py38\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cd /d C:\Users\C.Hezy\.cache\paddle_extensions && D:\software\Anaconda\envs\py38\python.exe iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\setup.py", line 20, in <module>
          import paddle3d
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\__init__.py", line 28, in <module>
          from . import datasets, models, transforms
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\datasets\__init__.py", line 16, in <module>
          from .kitti import KittiDepthDataset, KittiMonoDataset, KittiPCDataset
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\datasets\kitti\__init__.py", line 15, in <module>
          from .kitti_depth_det import KittiDepthDataset
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\datasets\kitti\kitti_depth_det.py", line 26, in <module>
          import paddle3d.transforms as T
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\transforms\__init__.py", line 19, in <module>
          from paddle3d.transforms.reader import *
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\transforms\reader.py", line 30, in <module>
          from paddle3d.models.detection.bevfusion.utils import generate_guassian_depth_target, map_pointcloud_to_image
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\models\__init__.py", line 18, in <module>
          from .heads import *
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\models\heads\__init__.py", line 16, in <module>
          from .dense_heads import *
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\models\heads\dense_heads\__init__.py", line 15, in <module>
          from .anchor3d_head import *
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\models\heads\dense_heads\anchor3d_head.py", line 23, in <module>
          from paddle3d.models.detection.bevfusion.utils import box3d_multiclass_nms
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\models\detection\bevfusion\utils.py", line 23, in <module>
          from paddle3d.ops.iou3d_nms_cuda import nms_gpu
        File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\ops\__init__.py", line 174, in __getattr__
          module = self._load_module()
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\ops\__init__.py", line 160, in _load_module
          self.module = self.jit_build()
        File "D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D\paddle3d\ops\__init__.py", line 147, in jit_build
          return paddle_jit_load(
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\cpp_extension.py", line 944, in load
          _jit_compile(file_path, verbose)
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1113, in _jit_compile
          run_cmd(compile_cmd, verbose)
        File "D:\software\Anaconda\envs\py38\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py", line 1155, in run_cmd
          raise RuntimeError("Failed to run command: {}, errors: {}".format(
      RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /d C:\Users\C.Hezy\.cache\paddle_extensions && D:\software\Anaconda\envs\py38\python.exe iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.
      Compiling user custom op, it will cost a few seconds.....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.



**Then I tried 'python C:\Users\C.Hezy\.cache\paddle_extensions\iou3d_nms_cuda_setup.py build', but still reported an error.
The specific issues are as follows:**


(py38) D:\software\Anaconda\envs\py38\Lib\site-packages\Paddle3D>python C:\Users\C.Hezy\.cache\paddle_extensions\iou3d_nms_cuda_setup.py build
running build
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'iou3d_nms_cuda' extension
E:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W0 /GL /DNDEBUG /MT -ID:\software\Anaconda\envs\py38\lib\site-packages\paddle\include -ID:\software\Anaconda\envs\py38\lib\site-packages\paddle\include\third_party "-ID:\software\CUDA_11.8\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -ID:\software\Anaconda\envs\py38\include -ID:\software\Anaconda\envs\py38\Include -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17763.0\shared" "-ID:\Windows Kits\10\include\10.0.17763.0\um" "-ID:\Windows Kits\10\include\10.0.17763.0\winrt" "-ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt" -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.14393.0\ucrt" /EHsc /Tpd:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_cpu.cpp /FoC:\Users\C.Hezy\.cache\paddle_extensions\iou3d_nms_cuda\iou3d_cpu.obj /MT /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /w /DGOOGLE_GLOG_DLL_DECL /DBOOST_HAS_STATIC_ASSERT /DNDEBUG /DPADDLE_USE_DSO -DPADDLE_WITH_CUSTOM_KERNEL -DPADDLE_WITH_CUDA
iou3d_cpu.cpp
D:\software\CUDA_11.8\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\thrust/detail/config/cpp_dialect.h:118: warning: Thrust requires at least MSVC 2019 (19.20/16.0/14.20). MSVC 2017 is deprecated but still supported. MSVC 2017 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
E:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W0 /GL /DNDEBUG /MT -ID:\software\Anaconda\envs\py38\lib\site-packages\paddle\include -ID:\software\Anaconda\envs\py38\lib\site-packages\paddle\include\third_party "-ID:\software\CUDA_11.8\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -ID:\software\Anaconda\envs\py38\include -ID:\software\Anaconda\envs\py38\Include -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17763.0\shared" "-ID:\Windows Kits\10\include\10.0.17763.0\um" "-ID:\Windows Kits\10\include\10.0.17763.0\winrt" "-ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt" -IE:\vs\2017\Community\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.14393.0\ucrt" /EHsc /Tpd:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp /FoC:\Users\C.Hezy\.cache\paddle_extensions\iou3d_nms_cuda\iou3d_nms.obj /MT /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /w /DGOOGLE_GLOG_DLL_DECL /DBOOST_HAS_STATIC_ASSERT /DNDEBUG /DPADDLE_USE_DSO -DPADDLE_WITH_CUSTOM_KERNEL -DPADDLE_WITH_CUDA
iou3d_nms.cpp
D:\software\CUDA_11.8\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\thrust/detail/config/cpp_dialect.h:118: warning: Thrust requires at least MSVC 2019 (19.20/16.0/14.20). MSVC 2017 is deprecated but still supported. MSVC 2017 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(119): error C2131: 表达式的计算结果不是常数
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(99): note: 因读取超过生命周期的变量而失败
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(99): note: 请参见“boxes_num”的用法
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(181): error C2131: 表达式的计算结果不是常数
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(157): note: 因读取超过生 命周期的变量而失败
d:\software\anaconda\envs\py38\lib\site-packages\paddle3d\paddle3d\ops\iou3d_nms\iou3d_nms.cpp(157): note: 请参见“boxes_num”的用法
error: command 'E:\\vs\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2


**Another issue is that I am using a Windows system, not a Linux system, and I am not sure if Paddle3D supports Windows systems.**

**Comment by lvpinrui** [comment]
hello,did you slove finally it?how to slove it?

**Comment by lvpinrui** [comment]
> hello,did you slove finally it?how to slove it?

**Comment by HezyC** [comment]
> > hello,did you slove finally it?how to slove it?

Sorry, I didn't solve this problem. You can try Ubuntu system

**Comment by warrentdrew** [comment]
hello, this may be due to cuda installation, might check if cuda bin and lib paths are correctly set in PATH and LD_LIBRARY_PATH environment variable. Also, paddle3d under Windows system is not fully tested, we'd suggest to use linux system.

**Comment by HezyC** [comment]
> hello, this may be due to cuda installation, might check if cuda bin and lib paths are correctly set in PATH and LD_LIBRARY_PATH environment variable. Also, paddle3d under Windows system is not fully tested, we'd suggest to use linux system.

Ok, thank you!
