### ISSUE TITLE
linux 安装报错

### ISSUE THREAD

**Issue by GDbbq** [PaddlePaddle/Paddle3D#334]
nvidia1080ti   cuda10.2 paddle-gpu 2.4.2  安装报错
(paddle) [root@plp-algorithm01 Paddle3D]# pip install -e .
Obtaining file:///data/linjiahui/projects/Paddle3D
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      /root/anaconda3/envs/paddle/lib/python3.8/site-packages/sklearn/utils/multiclass.py:13: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
        from scipy.sparse.base import spmatrix
      2023-05-18 09:15:29,717 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build
      gcc: 错误：unrecognized command line option ‘-std=c++14’
      /root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py:1214: UserWarning:
                                  **********************************
                                  *    ABI Compatibility WARNING   *
                                  **********************************
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
      Found that your compiler (g++ == 4.8.5) may be ABI-incompatible with pre-installed Paddle!
      Please use compiler that is ABI-compatible with GCC >= 5.4 (Recommended 8.2).
      
      See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html for ABI Compatibility
      information
      
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      
        warnings.warn(
      error: command '/usr/bin/gcc' failed with exit code 1
      2023-05-18 09:15:31,885 -    ERROR - iou3d_nms_cuda builded fail!
      Traceback (most recent call last):
        File "/data/linjiahui/projects/Paddle3D/paddle3d/ops/__init__.py", line 168, in _load_module
          self.module = importlib.import_module(self.modulename)
        File "/root/anaconda3/envs/paddle/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'iou3d_nms_cuda'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1152, in run_cmd
          return subprocess.check_call(command, shell=True, stdout=DEVNULL)
        File "/root/anaconda3/envs/paddle/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cd /root/.cache/paddle_extensions && /root/anaconda3/envs/paddle/bin/python iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/linjiahui/projects/Paddle3D/setup.py", line 20, in <module>
          import paddle3d
        File "/data/linjiahui/projects/Paddle3D/paddle3d/__init__.py", line 28, in <module>
          from . import datasets, models, transforms
        File "/data/linjiahui/projects/Paddle3D/paddle3d/datasets/__init__.py", line 16, in <module>
          from .kitti import KittiDepthDataset, KittiMonoDataset, KittiPCDataset
        File "/data/linjiahui/projects/Paddle3D/paddle3d/datasets/kitti/__init__.py", line 15, in <module>
          from .kitti_depth_det import KittiDepthDataset
        File "/data/linjiahui/projects/Paddle3D/paddle3d/datasets/kitti/kitti_depth_det.py", line 26, in <module>
          import paddle3d.transforms as T
        File "/data/linjiahui/projects/Paddle3D/paddle3d/transforms/__init__.py", line 19, in <module>
          from paddle3d.transforms.reader import *
        File "/data/linjiahui/projects/Paddle3D/paddle3d/transforms/reader.py", line 30, in <module>
          from paddle3d.models.detection.bevfusion.utils import generate_guassian_depth_target, map_pointcloud_to_image
        File "/data/linjiahui/projects/Paddle3D/paddle3d/models/__init__.py", line 18, in <module>
          from .heads import *
        File "/data/linjiahui/projects/Paddle3D/paddle3d/models/heads/__init__.py", line 16, in <module>
          from .dense_heads import *
        File "/data/linjiahui/projects/Paddle3D/paddle3d/models/heads/dense_heads/__init__.py", line 15, in <module>
          from .anchor3d_head import *
        File "/data/linjiahui/projects/Paddle3D/paddle3d/models/heads/dense_heads/anchor3d_head.py", line 23, in <module>
          from paddle3d.models.detection.bevfusion.utils import box3d_multiclass_nms
        File "/data/linjiahui/projects/Paddle3D/paddle3d/models/detection/bevfusion/utils.py", line 23, in <module>
          from paddle3d.ops.iou3d_nms_cuda import nms_gpu
        File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
        File "/data/linjiahui/projects/Paddle3D/paddle3d/ops/__init__.py", line 186, in __getattr__
          module = self._load_module()
        File "/data/linjiahui/projects/Paddle3D/paddle3d/ops/__init__.py", line 172, in _load_module
          self.module = self.jit_build()
        File "/data/linjiahui/projects/Paddle3D/paddle3d/ops/__init__.py", line 159, in jit_build
          return paddle_jit_load(
        File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/cpp_extension.py", line 944, in load
          _jit_compile(file_path, verbose)
        File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1113, in _jit_compile
          run_cmd(compile_cmd, verbose)
        File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1155, in run_cmd
          raise RuntimeError("Failed to run command: {}, errors: {}".format(
      RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /root/.cache/paddle_extensions && /root/anaconda3/envs/paddle/bin/python iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.
      Compiling user custom op, it will cost a few seconds.....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by GDbbq** [comment]
![image](https://github.com/PaddlePaddle/Paddle3D/assets/86715812/5688c2c5-93bf-465f-8371-7373106eb5f4)
![image](https://github.com/PaddlePaddle/Paddle3D/assets/86715812/14d93489-e9f9-4868-8fb2-0bd59a592f75)
![image](https://github.com/PaddlePaddle/Paddle3D/assets/86715812/4382388f-778a-45c9-8b95-376ebdb14e79)

**Comment by Xiaolong-RRL** [comment]
可能是gcc版本不匹配，可以参考这个解决办法：https://blog.csdn.net/qq_45779334/article/details/123169473

**Comment by cxy86121** [comment]
可能是cuda的环境变量设置有问题，可以参考https://github.com/PaddlePaddle/Paddle3D/issues/242#issuecomment-1459568371中的环境设置

**Comment by warrentdrew** [comment]
您好，应该是因为gcc版本较低的原因，建议升级到gcc 8.2或者使用paddle官方docker镜像
