### ISSUE TITLE
训练中间evalution的时候老是报CUDA_ERROR_OUT_OF_MEMORY的错误

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle3D#354]
环境信息，cuda版本为11.2
```
paddle-bfloat            0.1.7
paddle2onnx              1.0.6
paddledet                2.6.0
paddlepaddle-gpu         2.4.2.post112
paddleseg                2.8.0
x2paddle                 1.4.1
```
训练的时候使用--do_eval，每个若干个epoch就会进行evalution,。训练的时候显存使用正常，还有4G显存空闲。但每次evalution的时候，就会报错CUDA_ERROR_OUT_OF_MEMORY
```
2023-05-26 15:07:01,583 -     INFO - evaluate on validate dataset
2023-05-26 15:07:04,860 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build   ] 0.00%
Compiling user custom op, it will cost a few seconds.....
W0526 15:07:06.623517  4077 custom_operator.cc:723] Operator (hard_voxelize) has been registered.
2023-05-26 15:07:06,680 -     INFO - iou3d_nms_cuda builded success!
2023-05-26 15:14:41,644 -     INFO - [##################################################] 100.00%
/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py:20: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
Traceback (most recent call last):
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 864, in _attempt_allocation
    return allocator()
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 1075, in allocator
    driver.cuMemAlloc(byref(ptr), size)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 340, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 408, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Paddle3D/tools/train.py", line 207, in <module>
    main(args)
  File "Paddle3D/tools/train.py", line 202, in main
    trainer.train()
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/apis/trainer.py", line 336, in train
    eval_output = self.evaluate()
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/apis/trainer.py", line 426, in evaluate
    metrics = metric_obj.compute(verbose=True)
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/datasets/apollo/apollo_metric.py", line 203, in compute
    metric_r40_dict = apollo_eval(   # kitti_eval
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/__init__.py", line 42, in apollo_eval
    return get_official_eval_result(
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py", line 777, in get_official_eval_result
    metrics = do_eval_v3(
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py", line 681, in do_eval_v3
    ret = eval_class(
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py", line 522, in eval_class
    rets = calculate_iou_partly(
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py", line 423, in calculate_iou_partly
    overlap_part = bev_box_overlap(dt_boxes,
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/apollo_object_eval_python/apollo_eval.py", line 135, in bev_box_overlap
    riou = rotate_iou_gpu_eval(boxes, qboxes, criterion)
  File "/home/yanjiaxing/baidu/baidu/personal-code/paddle3d-apollo/Paddle3D/paddle3d/thirdparty/kitti_object_eval_python/rotate_iou.py", line 325, in rotate_iou_gpu_eval
    iou_dev = cuda.to_device(iou.reshape([-1]), stream)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 232, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/api.py", line 128, in to_device
    to, new = devicearray.auto_device(obj, stream=stream, copy=copy,
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py", line 876, in auto_device
    devobj = from_array_like(obj, stream=stream)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py", line 797, in from_array_like
    return DeviceNDArray(ary.shape, ary.strides, ary.dtype, stream=stream,
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/devicearray.py", line 103, in __init__
    gpu_data = devices.get_context().memalloc(self.alloc_size)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 1385, in memalloc
    return self.memory_manager.memalloc(bytesize)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 1077, in memalloc
    self._attempt_allocation(allocator)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 876, in _attempt_allocation
    return allocator()
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 1075, in allocator
    driver.cuMemAlloc(byref(ptr), size)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 340, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/yanjiaxing/anaconda3/envs/paddle_cuda11.2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 408, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY
```

**Comment by LielinJiang** [comment]
请问是哪个config？
