### ISSUE TITLE
使用container + 多卡训练时，每隔一定epoch就会报错并停止训练

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle3D#373]
系统环境：CentOS + 4 V100
container：paddle3d的容器
训练命令：
```
python -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py --config configs/centerpoint/centerpoint_pillars_02voxel_apollo.yml --save_dir output/centerpoint/centerpoint_voxels_010voxel_apollo_pillar_test_time_v100/ --save_interval 2 --num_workers 2 --keep_checkpoint_max 50
```
训练时，一开始正常没有问题，也可以正常保存weight。但是每次保存了2个权重，也就是训练了2个epoch之后，就会报下面的错误，然后训练停止
```
2023-06-18 01:35:04,503 -     INFO - [TRAIN] epoch=9/40, iter=103580/475840 , loss=3.660662, hm_loss=1.875750, hm_loss-0=0.300890, hm_loss-1=0.481469, hm_loss-2=0.476585, hm_loss-3=0.323238, hm_lo
ss-4=0.293567, loc_loss=1.784912, loc_loss-0=0.244127, loc_loss-1=0.215107, loc_loss-2=0.331872, loc_loss-3=0.462436, loc_loss-4=0.531370, num_positive=227.199997, num_positive-0=56.900002, num_po
sitive-1=22.000000, num_positive-2=41.799999, num_positive-3=36.200001, num_positive-4=70.300003, total_loss=3.656204, lr=0.000612 | ELA 03:51:26, ETA 76:25:35
LAUNCH WARNING 2023-06-18 01:35:32,593 save gpu log failed
LAUNCH WARNING 2023-06-18 01:38:13,911 save gpu log failed
2023-06-18 01:40:31,395 -     INFO - [TRAIN] epoch=9/40, iter=103590/475840 , loss=3.736970, hm_loss=1.907126, hm_loss-0=0.431099, hm_loss-1=0.406872, hm_loss-2=0.443714, hm_loss-3=0.343001, hm_lo
ss-4=0.282438, loc_loss=1.829844, loc_loss-0=0.243995, loc_loss-1=0.211365, loc_loss-2=0.355525, loc_loss-3=0.475029, loc_loss-4=0.543930, num_positive=230.600006, num_positive-0=41.000000, num_po
sitive-1=23.500000, num_positive-2=44.100002, num_positive-3=39.799999, num_positive-4=82.200005, total_loss=3.786171, lr=0.000612 | ELA 03:56:53, ETA 1734:27:58
2023-06-18 01:41:54,293 -     INFO - [TRAIN] epoch=9/40, iter=103600/475840 , loss=3.586809, hm_loss=1.838410, hm_loss-0=0.284668, hm_loss-1=0.455588, hm_loss-2=0.433800, hm_loss-3=0.337379, hm_lo
ss-4=0.326976, loc_loss=1.748398, loc_loss-0=0.223864, loc_loss-1=0.245048, loc_loss-2=0.295444, loc_loss-3=0.452919, loc_loss-4=0.531124, num_positive=221.500000, num_positive-0=48.799999, num_po
sitive-1=22.100000, num_positive-2=39.900002, num_positive-3=39.700001, num_positive-4=71.000000, total_loss=3.701564, lr=0.000612 | ELA 03:58:16, ETA 469:30:29
W0618 01:43:29.725286  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 01:43:29.733968  1089 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 01:43:48.874457  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2023-06-18 01:43:50,875 save gpu log failed
W0618 01:45:39.744014  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 01:45:39.743992  1089 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
2023-06-18 01:46:37,318 -     INFO - [TRAIN] epoch=9/40, iter=103610/475840 , loss=3.528522, hm_loss=1.743534, hm_loss-0=0.298492, hm_loss-1=0.417349, hm_loss-2=0.401019, hm_loss-3=0.344722, hm_lo
ss-4=0.281952, loc_loss=1.784988, loc_loss-0=0.220869, loc_loss-1=0.260880, loc_loss-2=0.310797, loc_loss-3=0.464220, loc_loss-4=0.528221, num_positive=199.699997, num_positive-0=39.000000, num_po
sitive-1=21.100000, num_positive-2=40.200001, num_positive-3=42.700001, num_positive-4=56.700001, total_loss=3.603586, lr=0.000612 | ELA 04:02:59, ETA 811:43:23
LAUNCH WARNING 2023-06-18 01:51:16,175 save gpu log failed
2023-06-18 01:51:40,470 -     INFO - [TRAIN] epoch=9/40, iter=103620/475840 , loss=3.649432, hm_loss=1.881318, hm_loss-0=0.340318, hm_loss-1=0.466921, hm_loss-2=0.400781, hm_loss-3=0.340941, hm_lo
ss-4=0.332356, loc_loss=1.768114, loc_loss-0=0.222663, loc_loss-1=0.221683, loc_loss-2=0.296246, loc_loss-3=0.481907, loc_loss-4=0.545614, num_positive=183.900009, num_positive-0=39.500000, num_po
sitive-1=23.800001, num_positive-2=34.900002, num_positive-3=34.299999, num_positive-4=51.400002, total_loss=3.820546, lr=0.000613 | ELA 04:08:02, ETA 2068:13:00
2023-06-18 01:53:06,899 -     INFO - [TRAIN] epoch=9/40, iter=103630/475840 , loss=3.562441, hm_loss=1.780607, hm_loss-0=0.301640, hm_loss-1=0.479340, hm_loss-2=0.417812, hm_loss-3=0.333877, hm_lo
ss-4=0.247939, loc_loss=1.781834, loc_loss-0=0.220330, loc_loss-1=0.222075, loc_loss-2=0.327004, loc_loss-3=0.480882, loc_loss-4=0.531543, num_positive=231.800003, num_positive-0=52.500000, num_po
sitive-1=22.000000, num_positive-2=50.400002, num_positive-3=44.700001, num_positive-4=62.200001, total_loss=3.620670, lr=0.000613 | ELA 04:09:29, ETA 1449:56:13
2023-06-18 01:58:50,277 -     INFO - [TRAIN] epoch=9/40, iter=103640/475840 , loss=3.744930, hm_loss=1.949739, hm_loss-0=0.389051, hm_loss-1=0.511498, hm_loss-2=0.406145, hm_loss-3=0.406196, hm_lo
ss-4=0.236850, loc_loss=1.795190, loc_loss-0=0.242608, loc_loss-1=0.227224, loc_loss-2=0.293727, loc_loss-3=0.484417, loc_loss-4=0.547213, num_positive=213.100006, num_positive-0=42.500000, num_po
sitive-1=22.200001, num_positive-2=38.900002, num_positive-3=37.200001, num_positive-4=72.300003, total_loss=3.713027, lr=0.000613 | ELA 04:15:12, ETA 2654:41:58
W0618 02:00:41.956030  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 02:01:46.584473  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 02:01:46.584470  1089 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
2023-06-18 02:02:00,153 -     INFO - [TRAIN] epoch=9/40, iter=103650/475840 , loss=3.718581, hm_loss=1.930346, hm_loss-0=0.297812, hm_loss-1=0.603741, hm_loss-2=0.362450, hm_loss-3=0.404028, hm_lo
ss-4=0.262315, loc_loss=1.788235, loc_loss-0=0.210398, loc_loss-1=0.261387, loc_loss-2=0.305840, loc_loss-3=0.472948, loc_loss-4=0.537662, num_positive=243.500000, num_positive-0=50.799999, num_po
sitive-1=21.900000, num_positive-2=40.500000, num_positive-3=40.900002, num_positive-4=89.400002, total_loss=3.637323, lr=0.000613 | ELA 04:18:22, ETA 173:19:39
2023-06-18 02:03:18,902 -     INFO - [TRAIN] epoch=9/40, iter=103660/475840 , loss=3.523426, hm_loss=1.751827, hm_loss-0=0.300081, hm_loss-1=0.395055, hm_loss-2=0.401649, hm_loss-3=0.368609, hm_lo
ss-4=0.286434, loc_loss=1.771598, loc_loss-0=0.245924, loc_loss-1=0.233960, loc_loss-2=0.313199, loc_loss-3=0.469702, loc_loss-4=0.508814, num_positive=227.400009, num_positive-0=68.900002, num_po
sitive-1=22.300001, num_positive-2=43.900002, num_positive-3=35.299999, num_positive-4=57.000000, total_loss=3.654517, lr=0.000613 | ELA 04:19:41, ETA 2714:32:12
LAUNCH WARNING 2023-06-18 02:03:53,739 save gpu log failed
W0618 02:04:21.807523  1042 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 02:04:21.807559  1089 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
2023-06-18 02:04:34,618 -     INFO - [TRAIN] epoch=9/40, iter=103670/475840 , loss=3.722369, hm_loss=1.912196, hm_loss-0=0.368280, hm_loss-1=0.433240, hm_loss-2=0.418735, hm_loss-3=0.328359, hm_lo
ss-4=0.363583, loc_loss=1.810173, loc_loss-0=0.251624, loc_loss-1=0.214851, loc_loss-2=0.319680, loc_loss-3=0.467465, loc_loss-4=0.556554, num_positive=203.000000, num_positive-0=46.500000, num_po
sitive-1=23.900000, num_positive-2=39.799999, num_positive-3=40.400002, num_positive-4=52.400002, total_loss=3.754025, lr=0.000613 | ELA 04:20:56, ETA 77:29:16
2023-06-18 02:05:37,092 -     INFO - [TRAIN] epoch=9/40, iter=103680/475840 , loss=3.469552, hm_loss=1.756241, hm_loss-0=0.250822, hm_loss-1=0.503595, hm_loss-2=0.411692, hm_loss-3=0.326161, hm_lo
ss-4=0.263971, loc_loss=1.713310, loc_loss-0=0.200774, loc_loss-1=0.218389, loc_loss-2=0.311061, loc_loss-3=0.465813, loc_loss-4=0.517274, num_positive=207.699997, num_positive-0=47.200001, num_po
sitive-1=19.800001, num_positive-2=31.300001, num_positive-3=45.000000, num_positive-4=64.400002, total_loss=3.728571, lr=0.000613 | ELA 04:21:59, ETA 211:11:34
LAUNCH INFO 2023-06-18 02:07:06,899 Pod failed                                                                                                                                              [5/1167]
LAUNCH ERROR 2023-06-18 02:07:06,900 Container failed !!!
Container rank 2 status failed cmd ['/usr/bin/python', '-u', 'tools/train.py', '--config', 'configs/centerpoint/centerpoint_pillars_02voxel_apollo.yml', '--save_dir', 'output/centerpoint/centerpoi
nt_voxels_010voxel_apollo_pillar_test_time_v100/', '--save_interval', '2', '--num_workers', '2', '--keep_checkpoint_max', '50', '--resume'] code 1 log log/workerlog.2 
env {'GREP_COLOR': '1;31', 'CUDNN_VERSION': '8.1.1.33', 'LC_ALL': 'en_US.UTF-8', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.7/dist-packages/cv2/../../lib64:/usr/local/TensorRT-8.0.3.4/lib:/usr/loc
al/cuda-11.2/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'LANG': 'en_US.UTF-8', 'HOSTNAME': '92c12e4ad2e1', 'OLDPWD': '/', 'WITH_GPU': 'ON', 'NVIDIA_VISIBLE_DEVICES': 
'all', 'NCCL_VERSION': '2.8.4', 'GOPATH': '/root/gopath', 'PWD': '/paddle3d_20230616', 'HOME': '/root', 'GOROOT': '/usr/local/go', 'CLICOLOR': '1', 'DEBIAN_FRONTEND': 'noninteractive', 'GREP_OPTIO
NS': '--color=auto', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'TERM': 'xterm', 'WITH_AVX': 'ON', 'CUDA_VERSION': '11.2.1', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'SHLVL': '1', 'LAN
GUAGE': 'en_US.UTF-8', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451', 'PATH': '/home/cmake-3.16.0-Linux-x86_64/bi
n:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/gopath/bin', 'PS1': '\\[\\033[1;33m\\]λ \\[\
\033[1;37m\\]\\h \\[\\033[1;32m\\]\\w \\[\\033[0m\\]', '_': '/usr/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib/python3.7/dist-packa
ges/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.7/dist-packages/cv2/qt/fonts', 'POD_NAME': 'dqaznl', 'PADDLE_MASTER': '169.254.30.5:63610', 'PADDLE_GLOBAL_SIZE': '4', 'PADDLE_LOCAL_
SIZE': '4', 'PADDLE_GLOBAL_RANK': '2', 'PADDLE_LOCAL_RANK': '2', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '169.254.30.5:63611,169.254.30.5:63612,169.254.30.5:63613,169.254.30.5:63614', 'P
ADDLE_CURRENT_ENDPOINT': '169.254.30.5:63613', 'PADDLE_TRAINER_ID': '2', 'PADDLE_TRAINERS_NUM': '4', 'PADDLE_RANK_IN_NODE': '2', 'FLAGS_selected_gpus': '2'}
LAUNCH INFO 2023-06-18 02:07:06,900 ------------------------- ERROR LOG DETAIL -------------------------
 - Finish CenterHead Initialization
2023-06-17 21:43:34,005 -     INFO - Resume model from checkpoint output/centerpoint/centerpoint_voxels_010voxel_apollo_pillar_test_time_v100/, current iter set to 71376
I0617 21:43:34.050737  1061 tcp_utils.cc:130] Successfully connected to 169.254.30.5:63610
2023-06-17 21:43:45,802 -  WARNING - No custom op voxelize found, try JIT build
Compiling user custom op, it will cost a few seconds.....
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
2023-06-17 21:43:58,186 -     INFO - voxelize builded success!
/paddle3d_20230616/paddle3d/datasets/apollo/apollo_utils.py:44: UserWarning: fake object!
  warnings.warn("fake object!")
W0618 01:43:29.725265  1091 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 01:45:39.743991  1091 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 02:01:46.584475  1091 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0618 02:04:21.807525  1091 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
Traceback (most recent call last):
  File "tools/train.py", line 207, in <module>
    main(args)
  File "tools/train.py", line 202, in main
    trainer.train()
  File "/paddle3d_20230616/paddle3d/apis/trainer.py", line 298, in train
    amp_cfg=self.amp_cfg)
  File "/paddle3d_20230616/paddle3d/apis/pipeline.py", line 66, in training_step
    outputs = model(sample)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddle3d_20230616/paddle3d/models/base/base_model.py", line 70, in forward
    return self.train_forward(samples, *args, **kwargs)
  File "/paddle3d_20230616/paddle3d/models/detection/centerpoint/centerpoint.py", line 110, in train_forward
    output = self.bbox_head.loss(samples, preds, self.test_cfg)
  File "/paddle3d_20230616/paddle3d/models/detection/centerpoint/center_head.py", line 300, in loss
    example['target_label'][task_id])
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddle3d_20230616/paddle3d/models/losses/focal_loss.py", line 103, in forward
    m_ind = paddle.concat(m_ind, axis=1)
  File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/manipulation.py", line 1140, in concat
    return _C_ops.concat(input, axis)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/multiprocess_utils.py", line 135, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 2131) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:188)
LAUNCH INFO 2023-06-18 02:07:28,618 Exit code -15
```
请问这是什么问题，应该怎么解决，感谢

**Comment by Birdylx** [comment]
@kamiLight 看报错信息里显示`bvar is busy at sampling for 2 seconds!`，有可能的原因：
1. 内存OOM，监控下训练过程中内存的使用情况，如果是该问题可以check一下dataset中是否使用了长list，可以将list转成numpy数据。
2. paddle版本问题，可以尝试下paddle2.4.2及以后的版本
