### ISSUE TITLE
 执行命令：“python ./deploy/smoke/python/infer.py --model_file ./output_kitti_inference/centerpoint.pdmodel --params_file ./output_kitti_inference/centerpoint.pdiparams --image ./datasets/KITTI/training/images_2/000425.png >  ./output_kitti/pred.txt  ”进行推理，报错：“I0603 07:01:28.572183  1454 analysis_predictor.cc:1314] ======= optimize end ======= I0603 07:01:28.572906  1454 naive_executor.cc:110] ---  skip [feed], feed -> data Traceback (most recent call last):   File "./deploy/smoke/python/infer.py", line 141, in <module>     pred = init_predictor(args)   File "./deploy/smoke/python/infer.py", line 106, in init_predictor     predictor = create_predictor(config) RuntimeError: (NotFound) Operator (hard_voxelize) is not registered.   [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:156) ”

### ISSUE THREAD

**Issue by domainsense** [PaddlePaddle/Paddle3D#468]

**Comment by weeeeeeee-der** [comment]
请问解决了吗
