### ISSUE TITLE
CADDN推理没反应

### ISSUE THREAD

**Issue by Lyric0620** [PaddlePaddle/Paddle3D#82]
`python infer.py --model_file D:/autodrive/Paddle3D/deploy/caddn/python/caddn.pdmodel --params_file D:/autodrive/Paddle3D/deploy/caddn/python/caddn.pdiparams --img_path D:/autodrive/YOLOPv2/data/10.jpg`
执行到`predictor = inference.create_predictor(config)`程序就结束了，没有报错也没有打印结果。

**Comment by dahwang22** [comment]
可以分享您的caddn.pdmodel和caddn.pdiparams文件么？

**Comment by Lyric0620** [comment]
@dahwang22 
`https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams`
直接用tools/export.py

**Comment by dahwang22** [comment]
@Gannis246 
我试过用这个转，会报错，你知道什么原因么？

(python38) root@386bd604215e:~/Project/Paddle3D:develop# python tools/export.py --config configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml --model deeplabv3_resnet101.pdparams
W0914 01:58:18.330529 59166 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0914 01:58:18.375120 59166 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "tools/export.py", line 69, in <module>
    main(args)
  File "tools/export.py", line 58, in main
    model = cfg.model
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/apis/config.py", line 178, in model
    self._model = self._load_object(model_cfg)
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/apis/config.py", line 283, in _load_object
    return component(**params)
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/models/detection/caddn/caddn.py", line 56, in __init__
    self.f2v = FrustumToVoxel(**f2v_cfg, disc_cfg=disc_cfg)
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/models/detection/caddn/f2v/frustum_to_voxel.py", line 39, in __init__
    self.grid_generator = FrustumGridGenerator(
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/models/detection/caddn/f2v/frustum_grid_generator.py", line 52, in __init__
    self.voxel_grid = create_meshgrid3d(
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle3d/utils/grid.py", line 34, in create_meshgrid3d
    xs = paddle.linspace(0, width - 1, width, dtype=dtype)
  File "/root/anaconda3/envs/python38/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 1573, in linspace
    return _C_ops.linspace(tensor_start, tensor_stop, tensor_num, 'dtype',
ValueError: (InvalidArgument) The num of linspace op should be larger than 0, but received num is 0
  [Hint: Expected num > 0, but received num:0 <= 0:0.] (at /paddle/paddle/phi/kernels/gpu/linspace_kernel.cu:101)
  [operator < linspace > error]

**Comment by wangna11BD** [comment]
我这边试了一下是可以正常导出的～
caddn模型需要编译paddle3d/ops下的自定义算子，可以检查一下看看是否编译。https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams只有一部分的模型参数，是用来初始化的，模型参数可以换成这个试试https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams试试
如果还是报错的话，可以发一下你的环境～

**Comment by wangna11BD** [comment]
> `python infer.py --model_file D:/autodrive/Paddle3D/deploy/caddn/python/caddn.pdmodel --params_file D:/autodrive/Paddle3D/deploy/caddn/python/caddn.pdiparams --img_path D:/autodrive/YOLOPv2/data/10.jpg` 执行到`predictor = inference.create_predictor(config)`程序就结束了，没有报错也没有打印结果。

测试环境 Ubuntu18.04， CUDA11.2， cuDNN8.1.1，python3.8，paddle2.3是可以正常运行出结果的。
可以发一下你的环境和测试图像吗

**Comment by dahwang22** [comment]
好的，谢谢您，应该是环境问题

**Comment by MySoulHub** [comment]
> 我这边试了一下是可以正常导出的～ caddn模型需要编译paddle3d/ops下的自定义算子，可以检查一下看看是否编译。[https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams只有一部分的模型参数，是用来初始化的，模型参数可以换成这个试试https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams试试](https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams%E5%8F%AA%E6%9C%89%E4%B8%80%E9%83%A8%E5%88%86%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%EF%BC%8C%E6%98%AF%E7%94%A8%E6%9D%A5%E5%88%9D%E5%A7%8B%E5%8C%96%E7%9A%84%EF%BC%8C%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%E5%8F%AF%E4%BB%A5%E6%8D%A2%E6%88%90%E8%BF%99%E4%B8%AA%E8%AF%95%E8%AF%95https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams%E8%AF%95%E8%AF%95) 如果还是报错的话，可以发一下你的环境～



> 我这边试了一下是可以正常导出的～ caddn模型需要编译paddle3d/ops下的自定义算子，可以检查一下看看是否编译。[https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams只有一部分的模型参数，是用来初始化的，模型参数可以换成这个试试https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams试试](https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams%E5%8F%AA%E6%9C%89%E4%B8%80%E9%83%A8%E5%88%86%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%EF%BC%8C%E6%98%AF%E7%94%A8%E6%9D%A5%E5%88%9D%E5%A7%8B%E5%8C%96%E7%9A%84%EF%BC%8C%E6%A8%A1%E5%9E%8B%E5%8F%82%E6%95%B0%E5%8F%AF%E4%BB%A5%E6%8D%A2%E6%88%90%E8%BF%99%E4%B8%AA%E8%AF%95%E8%AF%95https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams%E8%AF%95%E8%AF%95) 如果还是报错的话，可以发一下你的环境～

您好，请问有点云转深度图的脚本吗（kitti depth_2），主要想训练自己数据集

**Comment by wangna11BD** [comment]
可以参考Nuscenes 点云转depth 的代码： https://github.com/PaddlePaddle/Paddle3D/blob/1d846eed75641e056a239f675fc9e7451c3db408/paddle3d/models/detection/bevfusion/utils.py#L148
