### ISSUE TITLE
evaluate error centerpoint NVVM_ERROR_COMPILATION

### ISSUE THREAD

**Issue by unseenme** [PaddlePaddle/Paddle3D#88]
Project base:
https://aistudio.baidu.com/aistudio/projectdetail/4455993

Paddle 3D version:
dc2ce65dfd4297151e4f641266a79807285fd274

Evaluate command:

```
!python tools/evaluate.py --config configs/centerpoint/centerpoint_pillars_016voxel_minikitti.yml --model https://bj.bcebos.com/paddle3d/models/centerpoint//centerpoint_pillars_016voxel_kitti/model.pdparams --batch_size 1 --num_workers 3
```

Error:

```
Traceback (most recent call last):
  File "tools/evaluate.py", line 99, in <module>
    main(args)
  File "tools/evaluate.py", line 94, in main
    trainer.evaluate()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/apis/trainer.py", line 316, in evaluate
    metrics = metric_obj.compute(verbose=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/datasets/kitti/kitti_metric.py", line 160, in compute
    metric_types=["bbox", "bev", "3d"])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/__init__.py", line 11, in kitti_eval
    from paddle3d.thirdparty.kitti_object_eval_python.eval import get_official_eval_result
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/kitti_object_eval_python/eval.py", line 9, in <module>
    from .rotate_iou import rotate_iou_gpu_eval
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/kitti_object_eval_python/rotate_iou.py", line 262, in <module>
    def rotate_iou_kernel_eval(N, K, dev_boxes, dev_query_boxes, dev_iou, criterion=-1):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/decorators.py", line 101, in kernel_jit
    kernel.bind()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 548, in bind
    self._func.get()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 426, in get
    ptx = self.ptx.get()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 397, in get
    **self._extra_options)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 496, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 233, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 251, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 141, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (66, 23): parse expected comma after load's type
NVVM_ERROR_COMPILATION
```

**Comment by FlyingQianMM** [comment]
从报错信息来看，是第三方依赖库numba导入报错，确认您的环境是否有GPU，目前centerpoint只支持有GPU环境下运行。

另外numba可以安装 0.49.0的试试。

**Comment by unseenme** [comment]
项目直接从 Base Project https://aistudio.baidu.com/aistudio/projectdetail/4455993 Fork 出来，在 AI Studio 上运行的。
所以GPU是有的。

```
环境信息
硬件信息
CPU:
2核
AI加速卡:
v100
总显存:
16GB
总内存:
16 GB
总硬盘:
100 GB
```

重新Fork项目后，修改 requirements.txt 文件，安装了 numba 0.49.0 。
执行到模型评估的时候，问题依旧。

```
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
W0919 22:26:06.345651  7831 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0919 22:26:06.350137  7831 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2022-09-19 22:26:07,508 -     INFO - Finish CenterHead Initialization
2022-09-19 22:26:07,515 -     INFO - Load 994 Car database infos
2022-09-19 22:26:07,516 -     INFO - Load 161 Pedestrian database infos
2022-09-19 22:26:07,516 -     INFO - Load 50 Cyclist database infos
2022-09-19 22:26:07,516 -     INFO - After filtering min_num_points_in_box:
2022-09-19 22:26:07,516 -     INFO - Load 938 Car database infos
2022-09-19 22:26:07,516 -     INFO - Load 155 Pedestrian database infos
2022-09-19 22:26:07,516 -     INFO - Load 49 Cyclist database infos
2022-09-19 22:26:07,518 -     INFO - After filtering ignored difficulty:
2022-09-19 22:26:07,518 -     INFO - Load 725 Car database infos
2022-09-19 22:26:07,518 -     INFO - Load 149 Pedestrian database infos
2022-09-19 22:26:07,518 -     INFO - Load 43 Cyclist database infos
2022-09-19 22:26:07,519 -  WARNING - There is a file with the same name locally, we directly load the local file
2022-09-19 22:26:07,585 -     INFO - There are 191/191 variables loaded into CenterPoint.
2022-09-19 22:26:07,705 -     INFO - evaluate on validate dataset
2022-09-19 22:26:11,858 -  WARNING - No custom op voxelize found, try JIT build     ] 0.00%
Compiling user custom op, it will cost a few seconds.....
2022-09-19 22:26:14,327 -     INFO - voxelize builded success!
2022-09-19 22:26:16,351 -  WARNING - No custom op centerpoint_postprocess found, try JIT build
Compiling user custom op, it will cost a few seconds.....
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
W0919 22:26:26.196183  7831 custom_operator.cc:698] Operator (hard_voxelize) has been registered.
2022-09-19 22:26:26,213 -     INFO - centerpoint_postprocess builded success!
2022-09-19 22:26:32,729 -     INFO - ###############################################] 100.00%
Traceback (most recent call last):
  File "tools/evaluate.py", line 99, in <module>
    main(args)
  File "tools/evaluate.py", line 94, in main
    trainer.evaluate()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/apis/trainer.py", line 303, in evaluate
    metrics = metric_obj.compute(verbose=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/datasets/kitti/kitti_metric.py", line 163, in compute
    metric_types=["bbox", "bev", "3d"])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/__init__.py", line 11, in kitti_eval
    from paddle3d.thirdparty.kitti_object_eval_python.eval import get_official_eval_result
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/kitti_object_eval_python/eval.py", line 9, in <module>
    from .rotate_iou import rotate_iou_gpu_eval
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle3d-0.5.0-py3.7.egg/paddle3d/thirdparty/kitti_object_eval_python/rotate_iou.py", line 262, in <module>
    def rotate_iou_kernel_eval(N, K, dev_boxes, dev_query_boxes, dev_iou, criterion=-1):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/decorators.py", line 100, in kernel_jit
    kernel.bind()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 530, in bind
    self._func.get()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 407, in get
    ptx = self.ptx.get()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/compiler.py", line 378, in get
    **self._extra_options)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 495, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (66, 23): parse expected comma after load's type
NVVM_ERROR_COMPILATION
```

**Comment by FlyingQianMM** [comment]
看报错还是你的环境有些问题。重新建立一个干净的python 3.7的conda环境，然后再重装`numba 0.49.0`

**Comment by unseenme** [comment]
在aistudio上可以吗

**Comment by FlyingQianMM** [comment]
可以的，你现在用的也是conda，python35-paddle120-env是你现在用的conda环境名称
![image](https://user-images.githubusercontent.com/22235422/192415925-2f0c5890-9cd3-48a0-a1d0-46bc4015bdc1.png)

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
